/* tslint:disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
export const environment = {
  "production": true,
  "sitecoreApiHost": "http://localhost:3001",
  "sitecoreApiKey": "{7306CFF6-327E-43A8-B436-5FC86E31C92F}",
  "jssAppName": "my-first-jss-app-ang",
  "sitecoreLayoutServiceConfig": "jss",
  "defaultLanguage": "en",
  "defaultServerRoute": "/",
  "graphQLEndpointPath": "/api/my-first-jss-app-ang",
  "graphQLEndpoint": "http://localhost:3001/api/my-first-jss-app-ang?sc_apikey={7306CFF6-327E-43A8-B436-5FC86E31C92F}"
};
