// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
// tslint:disable

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { TranslateModule } from '@ngx-translate/core';
import { RouterModule } from '@angular/router';
import { GraphQLModule } from '../jss-graphql.module';
import { ContentBlockComponent } from './content-block/content-block.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { FooterComponent } from './footer/footer.component';
import { HeadersComponent } from './headers/headers.component';

@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    RouterModule,
    GraphQLModule,
    JssModule.withComponents([
      { name: 'ContentBlock', type: ContentBlockComponent },
      { name: 'Dashboard', type: DashboardComponent },
      { name: 'Footer', type: FooterComponent },
      { name: 'Headers', type: HeadersComponent },
    ]),
  ],
  exports: [
    CommonModule,
    TranslateModule,
    JssModule,
  ],
  declarations: [
    ContentBlockComponent,
    DashboardComponent,
    FooterComponent,
    HeadersComponent,
  ],
})
export class AppComponentsModule { }
